version: '3.8' # 2021.04現在

services:
  dfme:
    build: '.'
    ports:  # ポート転送(左: ローカルのポート, 右: コンテナ内のポート)
      - '50000:8888'  # Jupyter-notebook
    volumes:  # 共有フォルダのマウント(左: ローカルのパス, 右: コンテナ内のパス)
      - ../workspace:/workspace  # workspace
    working_dir: /workspace
    command: bash -c "jupyter notebook --allow-root"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 使用するGPUに合わせて変えること．複数指定可．
              # ex) ['0'],  ['0', '1', '3']
              device_ids: ['4']
              capabilities: [gpu]