# GPU required
# https://hub.docker.com/r/pytorch/pytorch
from pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

# # -----
# # Avoid GPG-key error 
# ENV TZ=Asia/Tokyo
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# RUN rm /etc/apt/sources.list.d/cuda.list
# RUN rm /etc/apt/sources.list.d/nvidia-ml.list
# RUN apt-key del 7fa2af80
# RUN apt-get update && apt-get install -y --no-install-recommends wget
# RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
# RUN dpkg -i cuda-keyring_1.0-1_all.deb
# # -----

# RUN     apt update && \
#         apt install -y \
#         libopencv-dev\
#         opencv-data

ADD     requirements.txt .
RUN     pip install --upgrade pip && \
        pip install -r requirements.txt
